In [2]:
#Date 31st Aug,2021
#creating arrays & matrix
import numpy as np

m=[4,8]; #single array

#2d array
A= [[1 ,2, 3], 
    [4, 5, 6], 
    [7, 8, 9]]

print('A = ',A)
print('A[0]=',A[0]) #1st row  
print('A[1]=',A[1]) #2nd row
print('A[2]=',A[2]) #3rd row
print('A[1][3]=',A[2][1]) #1st roaw , 3rd column
print('entire 1st column of A', A[:][0])
print('matrix m = ',m) 

r=3;#10 rows
c=3; #1o columns
B=[ ]

for i in range(r):
    for j in range(c):
        B=[[i,i+2,i+7],[j,j+3,j+4]];#2d arrary

print('matrix B =',B)        
print('matrix B = ',B[0][1]) #1st row and 2nd column of B


C=B + B;
print('matrix addition of B and B is BB=',C)


mat1 = np.array([[1, 2, 3, 4], [4, 5, 6, 8], [7, 6, 8, 9]])
print("Original matrix ");print(mat1)

print("Row from ")
print(mat1[0,:]) #1st row, all columns
print(mat1[1,2])#2nd row and 3rd column
print(mat1+mat1)





A =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
A[0]= [1, 2, 3]
A[1]= [4, 5, 6]
A[2]= [7, 8, 9]
A[1][3]= 8
entire 1st column of A [1, 2, 3]
matrix m =  [4, 8]
matrix B = [[2, 4, 9], [2, 5, 6]]
matrix B =  4
matrix addition of B and B is BB= [[2, 4, 9], [2, 5, 6], [2, 4, 9], [2, 5, 6]]
Original matrix 
[[1 2 3 4]
 [4 5 6 8]
 [7 6 8 9]]
Row from 
[1 2 3 4]
6
[[ 2  4  6  8]
 [ 8 10 12 16]
 [14 12 16 18]]
