In [2]:
#matrix multiplication

import numpy as np
from numpy.core.shape_base import atleast_2d
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
[r1,c1]=np.shape(mat1)
[r2,c2]=np.shape(mat1)

print(r1,c1)
print(mat1)
print(mat2)
res = np.dot(mat1,mat2)
print(res)

if c1==r2:
    print('yes')

##########################################################
result=([0, 0, 0],[0 ,0, 0],[0, 0, 0])

for i in range(r1):
    for j in range(c2):
        for k in range(r2):
            result[i][j]  = result[i][j]+ mat1[i][k]*mat2[k][j]

print(result)
###########################################################
A=np.arange(12).reshape(3,4)
print(A)
A2=np.arange(12).reshape(3,4)
print(A2)
B=np.arange(14)
print(B)
C=np.array([[2,3,4],[3,4,4]])
print(C)

D=np.matmul(C,A)
print('result matrix', D)

#multiplying by element by element
E=A*A2
print(E)



3 3
([1, 6, 5], [3, 4, 8], [2, 12, 3])
([3, 4, 6], [5, 6, 7], [6, 56, 7])
[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
yes
([63, 320, 83], [77, 484, 102], [84, 248, 117])
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[[2 3 4]
 [3 4 4]]
result matrix [[44 53 62 71]
 [48 59 70 81]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
