In [2]:
#Date 11 oct,2021
#creating arrays & matrix
import numpy as np

A=[1, 2, 3]
print(A)

M=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(M)
print(M[2][2])
print(M[2,2])
print(M[0,:])
print(M[:,0])

rm=len(M[:,0])
cn=len(M[0,:])
print(rm)
print(cn)

for i in range(rm):
    for j in range(cn):
        print(M[i,j])
        M[i,j]=M[i,j] + 1

print(M) 

for i in range(rm):
    for j in range(cn):
        print(M[i,j])
        M[i,j]=pow(M[i,j],2)

print(M)        
        

        

[1, 2, 3]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
9
9
[1 2 3]
[ 1  4  7 10]
4
3
1
2
3
4
5
6
7
8
9
10
11
12
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
2
3
4
5
6
7
8
9
10
11
12
13
[[  4   9  16]
 [ 25  36  49]
 [ 64  81 100]
 [121 144 169]]
