In [1]:
#creating matrix from user input
import numpy as np

m=input('enter number of row =')
n=input('enter number of col =')

A=np.mat('0 0 0 0;0 0 0 0')
print(A)
#A=np.array([[0,0,0],[0,0,0],[0,0,0]])
row=len(A)
print(row)
col=len(A[0])
print(col)
[row,col]=np.shape(A)
print(row,col)

for i in range(row):
    for j in range(col):
        A[i,j]=input('enter value  = ')  

print(A)
   

enter number of row =4
enter number of col =5
[[0 0 0 0]
 [0 0 0 0]]
2
1
2 4
enter value  = 4
enter value  = 5
enter value  = 6
enter value  = 4
enter value  = 5
enter value  = 5
enter value  = 5
enter value  = 5
[[4 5 6 4]
 [5 5 5 5]]
