In [4]:
import tensorflow as tf
print( ('your tensor flow version is: {0}').format(tf.__version__) )

your tensor flow version is: 2.6.0


In [17]:
A=tf.Variable([[4,3],[6,1]]);print(A)
B=tf.constant([[7,8],[4,5]]);print(B)
#concatenate column wise
AB_concatenated=tf.concat(values=[A,B], axis=1)
AB_concatenated

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>
tf.Tensor(
[[7 8]
 [4 5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]])>

In [18]:
#concatenate rows wise
AB_concatenated=tf.concat(values=[A,B], axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]])>

In [22]:
tensor=tf.ones(shape=[3,4],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [26]:
reshaped_tensor=tf.reshape(tensor=tensor,shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [34]:
import numpy as np
tensorR=tf.random.uniform(shape=[2,5],dtype=tf.float32)
tensorR

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.66648555, 0.5760162 , 0.80646515, 0.27309966, 0.98448896],
       [0.03935325, 0.8176042 , 0.5621226 , 0.910053  , 0.14898753]],
      dtype=float32)>

In [41]:
tensor=tf.constant([[4.6,4.2],
             [7.5,3.6],
             [2.7,9.4],
             [6.7,8.3],
            ], dtype=tf.float32)
tensor_as_int=tf.cast(tensor,dtype=tf.int32)
a=tf.transpose(tensor_as_int)
print(tensor,tensor_as_int,a)

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32) tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32) tf.Tensor(
[[4 7 2 6]
 [4 3 9 8]], shape=(2, 4), dtype=int32)


In [47]:
A=tf.constant([[5,8],
               [3,9]])
V=tf.constant([[4],
               [2]])
AV=tf.matmul(A,V)
Ac=tf.multiply(A,V)
r,c=A.shape
print(r);print(c)
AI=tf.eye(num_rows=4,num_columns=4)
print(AI)

2
2
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
